# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Gems
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Unfriendly Data
tagline:          
description:      'Machine Learning and fully automated luxury communism'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Aliaksandr Kazlou'
  url:            https://twitter.com/unfriendlydata

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
